export const types = {
    // Sync
    TASK_MANAGER_FILL_TASKS: 'TASK_MANAGER_FILL_TASKS',
    TASK_MANAGER_COMPLETING_TASK: 'TASK_MANAGER_COMPLETING_TASK',
    TASK_MANAGER_CREATING_TASK: 'TASK_MANAGER_CREATING_TASK',
    TASK_MANAGER_REMOVING_TASK: 'TASK_MANAGER_REMOVING_TASK',
    TASK_MANAGER_RENDER_ERROR_API_RESPONSE_MESSAGE: 'TASK_MANAGER_RENDER_ERROR_API_RESPONSE_MESSAGE',

    // Async
    TASK_MANAGER_FETCH_TASKS_ASYNC: 'TASK_MANAGER_FETCH_TASKS_ASYNC',
    TASK_MANAGER_REMOVE_TASK_ASYNC: 'TASK_MANAGER_REMOVE_TASK_ASYNC',
    TASK_MANAGER_CREATE_TASK_ASYNC: 'TASK_MANAGER_CREATE_TASK_ASYNC',
    TASK_MANAGER_COMPLETE_TASK_ASYNC: 'TASK_MANAGER_COMPLETE_TASK_ASYNC',
}
